services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
      -
    # сервис зависит от БД и redis
    depends_on:
      - db
      - redis
      -
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx.conf
      - static_volume:app/staticfoles
    # указываем что nginx зависит от сервисов web
    depends_on:
      - web

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    # том для хранения файлов redis
    volumes:
      - redis_date:/date
    env_file:
      - ./.env
  celery:
    build: .
    command:
      - celery -A config worker --loglevel-info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
  db:
    image: postgres:16
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

# объявляем тома для сохранения данных между перезапусками
volumes:
  postgres_data:
  static_volume:
  redis_date:
