# Generated by Django 6.0.7 on 2026-07-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Введите место привычки",
                        max_length=100,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Введите время привычки",
                        verbose_name="Время привычки",
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        blank=True,
                        help_text="Опишите действие привычки",
                        max_length=300,
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Опишите приятную привычку",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="Введите интервал между привычками",
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Опишите вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "completion_time",
                    models.IntegerField(
                        blank=True,
                        default=120,
                        help_text="Введите время выполнения привычки",
                        null=True,
                        verbose_name="Время выполнения",
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Опишите связанную с привычку с приятной",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
