# События
events {
    worker_connections 1024;
}

# основной http блок
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Сервер для django приложений
    upstream django {
        server web:8000;

    }

    server {
        listen 80; # работаем на порту 80
        server_name _; # Имя сервера оставляем по умолчанию

        # Определяем обработку запросов к статическим файлам
        location /static/ {
        alias /app/staticfiles/; # Указываем путь к статическим файлам в контейнере
        }

        # Проксируем остальные запросы к django приложениям
        location / {
            proxy_pass http://django;

            # Добавьте эти строки:
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
